<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AriController;
use App\Http\Controllers\RitController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\KspotController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\ScoreController;
use App\Http\Controllers\TspotController;
use App\Http\Controllers\FactorController;
use App\Http\Controllers\KvalueController;
use App\Http\Controllers\LogoutController;
use App\Http\Controllers\MethodController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\SampleController;
use App\Http\Controllers\TvalueController;
use App\Http\Controllers\BalanceController;
use App\Http\Controllers\PosbrixController;
use App\Http\Controllers\StationController;
use App\Http\Controllers\ActivityController;
use App\Http\Controllers\AnalysisController;
use App\Http\Controllers\ChemicalController;
use App\Http\Controllers\MaterialController;
use App\Http\Controllers\AnalisaPenilaianMbs;
use App\Http\Controllers\IndicatorController;
use App\Http\Controllers\KactivityController;
use App\Http\Controllers\TactivityController;
use App\Http\Controllers\ImbibitionController;
use App\Http\Controllers\AnalisaHplcController;
use App\Http\Controllers\AnalisaUmumController;
use App\Http\Controllers\CetakRonselController;
use App\Http\Controllers\SaccharomatController;
use App\Http\Controllers\AnalisaAmpasController;
use App\Http\Controllers\AnalisaKetelController;
use App\Http\Controllers\CetakBarcodeController;
use App\Http\Controllers\SampleResultController;
use App\Http\Controllers\StationResultController;
use App\Http\Controllers\AnalisaPosBrixController;
use App\Http\Controllers\ChemicalcheckingController;
use App\Http\Controllers\AplikasiPenerimaanController;

Route::get('/', HomeController::class)->name('home')->middleware(['auth']);
Route::resource('stations', StationController::class)->middleware(['auth']);
Route::resource('indicators', IndicatorController::class)->middleware(['auth']);
Route::resource('factors', FactorController::class)->middleware(['auth']);
Route::resource('materials', MaterialController::class)->middleware(['auth']);
Route::resource('samples', SampleController::class)->middleware(['auth']);
Route::resource('methods', MethodController::class)->middleware(['auth']);
Route::resource('analyses', AnalysisController::class)->middleware(['auth']);
Route::resource('users', UserController::class)->middleware(['auth']);
Route::resource('balances', BalanceController::class)->middleware(['auth']);
Route::resource('imbibitions', ImbibitionController::class)->middleware(['auth']);
Route::resource('kspots', KspotController::class)->middleware(['auth']);
Route::resource('kactivities', KactivityController::class)->middleware(['auth']);
Route::resource('kvalue', KvalueController::class)->middleware(['auth']);
Route::resource('tspots', TspotController::class)->middleware(['auth']);
Route::resource('tactivities', TactivityController::class)->middleware(['auth']);
Route::resource('tvalue', TvalueController::class)->middleware(['auth']);
Route::resource('chemicals', ChemicalController::class)->middleware(['auth']);
Route::resource('chemicalcheckings', ChemicalcheckingController::class)->middleware(['auth']);
Route::get('station_result/{station_id}', StationResultController::class)->name('station_result')->middleware(['auth']);
Route::get('sample_result/{material_id}', SampleResultController::class)->name('sample_result')->middleware(['auth']);
Route::get('report', [ ReportController::class, 'index' ])->name('report')->middleware(['auth']);
Route::post('report_process', [ ReportController::class, 'process' ])->name('report_process')->middleware(['auth']);
Route::get('login', [ LoginController::class, 'index' ])->name('login');
Route::post('login_process', [ LoginController::class, 'process' ])->name('login_process');
Route::get('logout', LogoutController::class)->name('logout');
Route::get('activities', ActivityController::class)->name('activities')->middleware(['auth']);
Route::get('saccharomat', [SaccharomatController::class, 'index'])->name('saccharomat')->middleware(['auth']);
Route::post('saccharomat_delete', [SaccharomatController::class, 'delete'])->name('saccharomat_delete')->middleware(['auth']);
Route::get('analisa_ampas', [AnalisaAmpasController::class, 'index'])->name('analisa_ampas')->middleware(['auth']);
Route::post('analisa_ampas_delete', [AnalisaAmpasController::class, 'delete'])->name('analisa_ampas_delete')->middleware(['auth']);
Route::get('analisa_umum', [AnalisaUmumController::class, 'index'])->name('analisa_umum')->middleware(['auth']);
Route::get('analisa_ketel', [AnalisaKetelController::class, 'index'])->name('analisa_ketel')->middleware(['auth']);
Route::get('analisa_hplc', [AnalisaHplcController::class, 'index'])->name('analisa_hplc')->middleware(['auth']);
Route::get('cetak_barcode', [CetakBarcodeController::class, 'index'])->name('cetak_barcode')->middleware(['auth']);
Route::get('cetak_ronsel', [CetakRonselController::class, 'index'])->name('cetak_ronsel')->middleware(['auth']);
Route::post('saccharomat_store', [SaccharomatController::class, 'store'])->name('saccharomat_store')->middleware(['auth']);
Route::post('analisa_ampas_store', [AnalisaAmpasController::class, 'store'])->name('analisa_ampas_store')->middleware(['auth']);
Route::post('analisa_umum_store', [AnalisaUmumController::class, 'store'])->name('analisa_umum_store')->middleware(['auth']);
Route::post('analisa_ketel_store', [AnalisaKetelController::class, 'store'])->name('analisa_ketel_store')->middleware(['auth']);
Route::post('analisa_hplc_store', [AnalisaHplcController::class, 'store'])->name('analisa_hplc_store')->middleware(['auth']);
Route::post('cetak_barcode_store', [CetakBarcodeController::class, 'store'])->name('cetak_barcode_store')->middleware(['auth']);
Route::post('cetak_ronsel_store', [CetakRonselController::class, 'store'])->name('cetak_ronsel_store')->middleware(['auth']);



Route::resource('rits', RitController::class)->middleware(['auth']);
Route::resource('posbrixes', PosbrixController::class)->middleware(['auth']);
Route::resource('aris', AriController::class)->middleware(['auth']);
Route::resource('scores', ScoreController::class)->middleware(['auth']);

Route::get('rit', AplikasiPenerimaanController::class)->name('rit')->middleware(['auth']);
Route::get('posbrix', AnalisaPosBrixController::class)->name('posbrix')->middleware(['auth']);
Route::get('score', AnalisaPenilaianMbs::class)->name('score')->middleware(['auth']);
