<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\LogoutController;
use App\Http\Controllers\MethodController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\SampleController;
use App\Http\Controllers\StationController;
use App\Http\Controllers\ActivityController;
use App\Http\Controllers\AnalysisController;
use App\Http\Controllers\MaterialController;
use App\Http\Controllers\IndicatorController;
use App\Http\Controllers\SaccharomatController;
use App\Http\Controllers\AnalisaAmpasController;
use App\Http\Controllers\SampleResultController;
use App\Http\Controllers\StationResultController;
use App\Http\Controllers\MonitoringAnalisaPerTanggalController;

Route::get('/', HomeController::class)->name('home')->middleware(['auth']);
Route::resource('stations', StationController::class);
Route::resource('indicators', IndicatorController::class);
Route::resource('materials', MaterialController::class);
Route::resource('samples', SampleController::class);
Route::resource('methods', MethodController::class);
Route::resource('analyses', AnalysisController::class);
Route::resource('users', UserController::class);
Route::get('station_result/{station_id}', StationResultController::class)->name('station_result');
Route::get('sample_result/{material_id}', SampleResultController::class)->name('sample_result');
Route::get('report', [ ReportController::class, 'index' ])->name('report');
Route::post('report_process', [ ReportController::class, 'process' ])->name('report_process');
Route::get('login', [ LoginController::class, 'index' ])->name('login');
Route::post('login_process', [ LoginController::class, 'process' ])->name('login_process');
Route::get('logout', LogoutController::class)->name('logout');
Route::get('activities', ActivityController::class)->name('activities');
Route::get('saccharomat', [SaccharomatController::class, 'index'])->name('saccharomat');
Route::get('analisa_ampas', [AnalisaAmpasController::class, 'index'])->name('analisa_ampas');
Route::post('saccharomat_store', [SaccharomatController::class, 'store'])->name('saccharomat_store');
Route::post('analisa_ampas_store', [AnalisaAmpasController::class, 'store'])->name('analisa_ampas_store');
